# Generated by Django 2.1.14 on 2019-11-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegroupobjectpermission',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articleuserobjectpermission',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
