# Generated by Django 3.0.3 on 2020-02-05 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_uuidpkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithBinaryField',
            fields=[
                ('content', models.BinaryField(null=True)),
            ],
        ),
    ]
