# Generated by Django 5.2.5 on 2025-10-20 14:46

from django.db import migrations

import guardian.testapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0009_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ULIDPKModel",
            fields=[
                (
                    "ulid_pk",
                    guardian.testapp.models.ULIDField(
                        default=guardian.testapp.models.default_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
