# Generated by Django 2.2.7 on 2019-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_generic_permissions_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
