# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_pk_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='object_pk',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='object_pk',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
