# Generated by Django 2.2.2 on 2025-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_generic_permissions_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userobjectpermission',
            index=models.Index(
                fields=['permission', 'user', 'content_type', 'object_pk'],
                name='guardian_us_perm_user_ct_obj_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='groupobjectpermission',
            index=models.Index(
                fields=['permission', 'group', 'content_type', 'object_pk'],
                name='guardian_gr_perm_group_ct_obj_idx',
            ),
        ),
    ]