# Generated by Django 2.2.23 on 2022-06-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0003_pk_to_int_from_makemigrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='object_pk',
            field=models.CharField(max_length=255, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='object_pk',
            field=models.CharField(max_length=255, verbose_name='object ID'),
        ),
    ]
